import {
  adminCategoriesLawsRootPath,
  adminReportsPath,
  adminSocialMediaFormPath,
  adminSocialMediaPath,
} from '~/main/utils/admin-routes.utils';
import type { RouteLocationNormalizedGeneric } from '#vue-router';
import { UserRoles } from '~/core/auth/constants/user-roles';

export const APP_ROUTES = {
  web: {
    prices: {
      root: 'prices',
    },
    joinUs: {
      root: {
        name: 'join-us',
        path: '/join-us',
        permissions: {
          allowAdmin: true,
          allowStudent: true,
          allowEmployee: true,
          allowUser: true,
          isAuth: false,
        },
      },
    },
    registerTrainer: {
      root: {
        name: 'register-trainer',
        path: '/register-trainer',
        permissions: {
          allowAdmin: true,
          allowStudent: true,
          allowEmployee: true,
          allowUser: true,
          isAuth: false,
        },
      },
    },
    registerStudent: {
      root: {
        name: 'register-student',
        path: '/register-student',
        permissions: {
          allowAdmin: true,
          allowStudent: true,
          allowEmployee: true,
          allowUser: true,
          isAuth: false,
        },
      },
    },
    registerSchool: {
      root: {
        name: 'register-school',
        path: '/register-school',
        permissions: {
          allowAdmin: true,
          allowStudent: true,
          allowEmployee: true,
          allowUser: true,
          isAuth: false,
        },
      },
    },
  },
  admin: {
    root: 'ekht-admin',
    categoriesLaws: {
      root: 'laws',
    },
    reports: {
      root: 'reports',
    },
    socialMedia: {
      root: 'social-media',
      form: 'form',
    },
    coupon: {
      root: 'coupons',
    },
    students: {
      root: 'students',
    },
    surveys: {
      root: 'surveys',
      show: 'show',
    },
    lessonsCategory:{
      root:'lessonsCategory',
    }
  },
  userDashboard:{
    root:'user-dashboard',
    foundations:{
      root:'foundations',
      lesson:'lesson'
    },
    prepare: {
      path: 'prepare',
    },
    steps: {
      root: 'steps',
    },
    analytics:{
      root:'analytics'
    }

  }
};

export const EXAM_QUESTIONS_ROUTES = {
  root: 'exam-questions',
};

export const routersWithoutTypeSelect = [
  '/general-selection',
  '/exam-questions',
  '/ekht-admin',
  '/competition',
  '/student',
  '/question-today',
];

export const all_routers = [
  {
    path: '',
    name: 'home',
    allowAdmin: true,
    allowStudent: true,
    allowEmployee: true,
    allowTeacher: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: `/:overview`,
    name: `overview`,
    allowAdmin: true,
    allowStudent: true,
    allowEmployee: true,
    allowTeacher: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/features',
    name: 'features',
    allowAdmin: true,
    allowStudent: true,
    allowEmployee: true,
    allowTeacher: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/subscriptions',
    name: 'subscriptions',
    allowAdmin: true,
    allowStudent: true,
    allowEmployee: true,
    allowTeacher: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/faqs',
    name: 'faqs',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/privacy',
    name: 'privacy',
    allowAdmin: true,
    allowStudent: true,
    allowEmployee: true,
    allowTeacher: true,
    allowUser: true,
    isAuth: false,
  },
  {
    name: APP_ROUTES.web.joinUs.root.name,
    path: APP_ROUTES.web.joinUs.root.path,
    ...APP_ROUTES.web.joinUs.root.permissions,
  },
  {
    name: APP_ROUTES.web.registerTrainer.root.name,
    path: APP_ROUTES.web.registerTrainer.root.path,
    ...APP_ROUTES.web.registerTrainer.root.permissions,
  },
  {
    name: APP_ROUTES.web.registerStudent.root.name,
    path: APP_ROUTES.web.registerStudent.root.path,
    ...APP_ROUTES.web.registerStudent.root.permissions,
  },
  {
    name: APP_ROUTES.web.registerSchool.root.name,
    path: APP_ROUTES.web.registerSchool.root.path,
    ...APP_ROUTES.web.registerSchool.root.permissions,
  },
  {
    path: '/about-us',
    name: 'about-us',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/conditions',
    name: 'conditions',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/contact-us',
    name: 'contact-us',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/complaints',
    name: 'complaints',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/set-password',
    name: 'set-password',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/confirm-payment',
    name: 'confirm-payment',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: '/payment-redirect',
    name: 'payment-redirect',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: '/blog',
    name: 'blog',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/404',
    name: '404',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/question-today/:id',
    name: 'question-today',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/prices',
    name: 'prices',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/competition/:id',
    name: 'competition',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: '/general-selection',
    name: 'general-selection',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: `/${EXAM_QUESTIONS_ROUTES.root}/:id/:title`,
    name: EXAM_QUESTIONS_ROUTES.root,
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isPublic: true,
    isAuth: false,
  },
  {
    path: '/exam-questions-test/:id/:title',
    name: 'exam-questions-test',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isPublic: true,
    isAuth: false,
  },
  {
    path: '/question-animate/:id',
    name: 'question-animate',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isPublic: true,
    isAuth: false,
  },
  {
    path: '/partnership-conditions',
    name: 'partnership-conditions',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: `/${APP_ROUTES.admin.root}`,
    name: `admin`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/categories`,
    name: `categories`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: adminCategoriesLawsRootPath(),
    name: 'laws',
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: adminSocialMediaPath(),
    name: 'social-media',
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: adminSocialMediaFormPath(),
    name: 'social-media-form',
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: adminReportsPath(),
    name: APP_ROUTES.admin.reports.root,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/law-manage`,
    name: 'law-manager',
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/services-manage`,
    name: 'services-manager',
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/employees`,
    name: `employees`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/exams`,
    name: `exams`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/exams/:id`,
    name: `exams`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/exams/:id/questions/:partId`,
    name: `exam-questions`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/exams/form`,
    name: `exams`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/competitions`,
    name: `competitions`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/competitions/:id`,
    name: `competitions`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/competitions/:id/questions/:partId`,
    name: `competition-questions`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/competitions/form`,
    name: `competitions`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/faqs`,
    name: `faqs`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/general-info`,
    name: `general-info`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/static-page`,
    name: `static-page`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/contact-us`,
    name: `manage-contact-us`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/complains`,
    name: `manage-complains`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/questions`,
    name: `questions`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/questions/add-question`,
    name: `questions`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/questions/add-question-new`,
    name: 'add-question',
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/questions/edit-question`,
    name: `edit-questions`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/subjects`,
    name: `subjects`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/videos-lib`,
    name: `videosLab`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/subscriptions`,
    name: `subscriptions`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/c-panel`,
    name: `c-panel`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/upload-questions`,
    name: `upload-questions`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/upload-questions-tahsili`,
    name: `upload-questions-tahsili`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/chat`,
    name: `chat`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/site-map`,
    name: `site-map`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/tags-manage`,
    name: `tags-manage`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/partnerships`,
    name: `partnerships-manage`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/${APP_ROUTES.admin.lessonsCategory.root}`,
    name: `lessonsCategory`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/student/change-password`,
    name: `change-password`,
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },

  {
    path: '/student/exams',
    name: 'std-exams',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/exams-filter',
    name: 'std-exams-filter',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/student/external-exams-filter',
    name: 'std-external-exams-filter',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/student/exams/processing',
    name: 'std-exams-processing',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/exams/subjects',
    name: 'std-exams-subjects',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/exams/will-do',
    name: 'std-exams-will-do',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/exams/done',
    name: 'std-exams-done',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/exams/details/:id',
    name: 'std-exams-will-details',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/exams/exam-result/:id',
    name: 'std-exam-result',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/exams/:id',
    name: 'std-exams-id',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },

  {
    path: '/student/training',
    name: 'std-training',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/training/processing',
    name: 'std-training-processing',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/training/subjects',
    name: 'std-training-subjects',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/training/will-do',
    name: 'std-training-will-do',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/training/done',
    name: 'std-training-done',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/training/details/:id',
    name: 'std-training-will-details',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/training/:id',
    name: 'std-training-id',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/training/review/:id',
    name: 'std-training-review',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/student/training/passed-detail/:id`,
    name: 'std-training-passed-detail',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/profile',
    name: 'profile',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: '/student/rate',
    name: 'rate',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: '/student/student-status',
    name: 'student-status',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: '/student/challenges',
    name: 'challenges',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: '/student/challenges/:id',
    name: 'challenge-details',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: '/student/questions-review',
    name: 'questions-review',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/student/analytics/:id',
    name: 'student-analytics',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/tag2/:title/:exam-info',
    name: 'std-exam-info',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: `/${APP_ROUTES.admin.root}/blogs`,
    name: `blogs`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/blogs/categories`,
    name: `blogs-categories`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/blogs/tags`,
    name: `blogs-tags`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/site-content`,
    name: `site-content`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/site-content/:name`,
    name: `json-file`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/media-manage`,
    name: `media-manage`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/coupons`,
    name: `coupon-manage`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/students`,
    name: `students-manage`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/students/:id`,
    name: `student-trainings`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/students/:id/:tid`,
    name: `student-training-details`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.admin.root}/students/:id/subscriptions`,
    name: `student-subscriptions`,
    allowAdmin: true,
    allowStudent: false,
    allowTeacher: false,
    allowEmployee: false,
    allowUser: false,
    isAuth: true,
  },
  {
    path: '/user-panel',
    name: 'user-panel',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.userDashboard.root}`,
    name: 'user-dashboard',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.userDashboard.root}/${APP_ROUTES.userDashboard.foundations.root}`,
    name: 'foundation',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.userDashboard.root}/${APP_ROUTES.userDashboard.prepare.path}`,
    name: 'prepare',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: true,
  },
  {
    path: '/tracks',
    name: 'tracks',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/tracks/:id',
    name: 'track-details',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/partnerships',
    name: 'partnerships',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/partnerships/school',
    name: 'partnerships-school',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/partnerships/student',
    name: 'partnerships-student',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: '/partnerships/teacher',
    name: 'partnerships-teacher',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: true,
    isAuth: false,
  },
  {
    path: `/${APP_ROUTES.userDashboard.root}/${APP_ROUTES.userDashboard.foundations.root}`,
    name: 'user-foundation',
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isPublic: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.userDashboard.root}/${APP_ROUTES.userDashboard.foundations.root}/${APP_ROUTES.userDashboard.foundations.lesson}/:id`,
    name: 'user-lesson',  
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isPublic: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.userDashboard.root}/${APP_ROUTES.userDashboard.foundations}/${APP_ROUTES.userDashboard.foundations.lesson}/:id/:details`,
    name: 'user-lesson-details',  
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isPublic: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.userDashboard.root}/${APP_ROUTES.userDashboard.steps.root}`,
    name: 'user-steps',  
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isPublic: false,
    isAuth: true,
  },
  {
    path: `/${APP_ROUTES.userDashboard.root}/${APP_ROUTES.userDashboard.analytics.root}`,
    name: 'user-analytics',  
    allowAdmin: true,
    allowStudent: true,
    allowTeacher: true,
    allowEmployee: true,
    allowUser: false,
    isPublic: false,
    isAuth: true,
  },
];


export const needAuth = (route: RouteLocationNormalizedGeneric): boolean => {
  const currentRouter = all_routers.filter(
    (r) => r.path == route.matched[0]?.path
  )[0];
  return currentRouter?.isAuth ?? false;
};

export const isAllowRouter = (
  route: RouteLocationNormalizedGeneric,
  userRole: UserRoles
) => {
  const currentRouter = all_routers.filter(
    (r) => r.path == route.matched[0]?.path || route.fullPath
  )[0];
  switch (userRole) {
    case UserRoles.admin:
    case UserRoles.mediaManager: {
      return currentRouter.allowAdmin;
    }
    case UserRoles.employee: {
      return currentRouter.allowEmployee;
    }
    case UserRoles.student: {
      return currentRouter.allowStudent;
    }
    case UserRoles.teacher: {
      return currentRouter.allowTeacher;
    }
    case UserRoles.user: {
      return currentRouter.allowUser;
    }
  }
};
