export enum ServiceTypesEnum {
  TRAININGBYCATEGORY = 'TRAININGBYCATEGORY',
  FULLEXAM = 'FULLEXAM',
  EXAMBYCATEGORY = 'EXAMBYCATEGORY',
  BANKUSAGE = 'BANKUSAGE',
  TAKFELATUSAGE = 'TAKFELATUSAGE',
  HELPINPRACTICE = 'HELPINPRACTICE',
  SHOWSOLVESOLUATION = 'SHOWSOLVESOLUATION',
  FAVORITEUSAGE = 'FAVORITEUSAGE',
  ROWNQUESTIONPRACTICE = 'ROWNQUESTIONPRACTICE',
  LEVELQUESTIONPRACTICE = 'LEVELQUESTIONPRACTICE',
  ANALAZEDEGRE = 'ANALAZEDEGRE',
  ANALAZENUMBERCATEGORY = 'ANALAZENUMBERCATEGORY',
}
