/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeBlockUI: (typeof import('primevue/blockui'))['default'];
    PrimeTabPanel: (typeof import('primevue/tabpanel'))['default'];
    PrimeTabPanels: (typeof import('primevue/tabpanels'))['default'];
    PrimeTabList: (typeof import('primevue/tablist'))['default'];
    PrimeTabs: (typeof import('primevue/tabs'))['default'];
    PrimeTab: (typeof import('primevue/tab'))['default'];
    PrimeSkeleton: (typeof import('primevue/skeleton'))['default'];
    PrimeCard: (typeof import('primevue/card'))['default'];
    PrimeButton: (typeof import('primevue/button'))['default'];
    PrimeDialog: (typeof import('primevue/dialog'))['default'];
    PrimeToast: (typeof import('primevue/toast'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
}
