/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    //prime
    'PrimeDatePicker': (typeof import('primevue/datepicker'))['default'];
    //table
    'PrimeDataTable': (typeof import('primevue/datatable'))['default'];
    'PrimeColumn': (typeof import('primevue/column'))['default'];
    'PrimeColumnGroup': (typeof import('primevue/columngroup'))['default'];
    'PrimeRow': (typeof import('primevue/row'))['default'];
    //end table
    'prime-tooltip': (typeof import('primevue/tooltip'))['default'];
    PrimeCheckbox: (typeof import('primevue/checkbox'))['default'];
    PrimeToggleSwitch: (typeof import('primevue/toggleswitch'))['default'];
    PrimePopover: (typeof import('primevue/popover'))['default'];
    //accordion
    PrimeAccordionContent: (typeof import('primevue/accordioncontent'))['default'];
    PrimeAccordionHeader: (typeof import('primevue/accordionheader'))['default'];
    PrimeAccordionPanel: (typeof import('primevue/accordionpanel'))['default'];
    PrimeAccordion: (typeof import('primevue/accordion'))['default'];
    //end accordion
    //tabs
    PrimeTabPanel: (typeof import('primevue/tabpanel'))['default'];
    PrimeTabPanels: (typeof import('primevue/tabpanels'))['default'];
    PrimeTabList: (typeof import('primevue/tablist'))['default'];
    PrimeTabs: (typeof import('primevue/tabs'))['default'];
    PrimeTab: (typeof import('primevue/tab'))['default'];
    //end tabs
    PrimeSkeleton: (typeof import('primevue/skeleton'))['default'];
    PrimeCard: (typeof import('primevue/card'))['default'];
    PrimeButton: (typeof import('primevue/button'))['default'];
    PrimeDialog: (typeof import('primevue/dialog'))['default'];
    PrimeToast: (typeof import('primevue/toast'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
}
