/** @type {import('tailwindcss').Config} */
const plugin = require('tailwindcss/plugin')

module.exports = {
  darkMode: 'class',
  watcher: {
    usePolling: false, // أو true على حسب النظام
  },
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.{vue,js,html}',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
  ],
   plugins: [
    plugin(function({ addVariant }) {
      addVariant('max-sm', '@media (max-width: 640px)')
    })
  ],
  theme: {
    screens: {
      sm: '640px',

      md: '768px',

      lg: '992px',

      xl: '960px', //desktop start

      'xl1200':'1200px',

      '2xl': '1400px',
    },
    extend: {
      boxShadow: {
        'custom': '0px 0px 10px #00000029',
        'custom-dark': '-4px 0px 10px rgba(0, 0, 0, 0.16)',
      },
      colors: {
        'purple-8d': 'var(--purple-8d)',
        'purple-af': 'var(--purple-af)',
        'pink-ff': 'var(--pink-ff)',
        'purple-e0': 'var(--purple-e0)',
        'green-8c': 'var(--green-8c)',
        'dark-63': 'var(--dark-63)',
        'dark-44': 'var(--dark-44)',
        'dark-37': 'var(--dark-37)',
        'gray-be': 'var(--gray-be)',
        'gray-d1': 'var(--gray-d1)',
        'gray-fa': 'var(--gray-fa)',
        'gray-8b': 'var(--gray-8b)',
        'orange-39': 'var(--orange-39)',
        'gray-f2': 'var(--gray-f2)',
        'red-63': 'var(--red-63)',
        'yellow-42': 'var(--yellow-42)',
        'blue-f7': 'var(--blue-f7)',
        'blue-f1': 'var(--blue-f1)',
        'black-20': 'var(--black-20)',
        'black-24': 'var(--black-24)',
        'black-29': 'var(--black-29)',
        'white-ff': 'var(--white-ff)',
        'gray-8f': 'var(--gray-8f)',
        'gray-29': 'var(--gray-29)',
        'gray-ff': 'var(--gray-ff)',
        'gray-f7': 'var(--gray-f7)',
        'gray-97': 'var(--gray-97)',
        'gray-fb': 'var(--gray-fb)',
        'gray-fc': 'var(--gray-fc)',
        'gray-f3': 'var(--gray-f3)',
        'gray-ea': 'var(--gray-ea)',
        'gray-ed': 'var(--gray-ed)',
        'gray-e0': 'var(--gray-e0)',
        'gray-99': 'var(--gray-99)',
        'gray-91': 'var(--gray-91)',
        'gray-d3': 'var(--gray-d3)',
        'gray-f4': 'var(--gray-f4)',
        'gray-f5': 'var(--gray-f5)',
        'gray-cc': 'var(--gray-cc)',
        'gray-7cc': 'var(--gray-7cc)',
        'gray-9c': 'var(--gray-9c)',
        'gray-1a': 'var(--gray-1a)',
        'gray-f6': 'var(--gray-f6)',
        'gray-de': 'var(--gray-de)',
        'gray-ee': 'var(--gray-ee)',
        'gray-e2': 'var(--gray-e2)',
        'gray-d5': 'var(--gray-d5)',
        'gray-b5': 'var(--gray-b5)',
        'gray-c7': 'var(--gray-c7)',
        'gray-2f2': 'var(--gray-2f2)',
        'gray-63': 'var(--gray-63)',
        'gray-f9': 'var(--gray-f9)',
        'gray-eb': 'var(--gray-eb)',
        'dark-1e': 'var(--dark-1e)',
        'dark-2b': 'var(--dark-2b)',
        'dark-1d': 'var(--dark-1d)',
        'dark-26': 'var(--dark-26)',
        'dark-32': 'var(--dark-32)',
        'dark-45': 'var(--dark-45)',
        'dark-56': 'var(--dark-56)',
        'text-8c': 'var(--text-8c)',
        'text-4d': 'var(--text-4d)',
        'purple-e8': 'var(--purple-e8)',
        'purple-c2': 'var(--purple-c2)',
        'purple-f1': 'var(--purple-f1)',
        'purple-e6': 'var(--purple-e6)',
        'purple-8c':'var(--purple-8c)',
        'purple-78':'#300378',
        'red-81': 'var(--red-81)',
        'red-5e': 'var(--red-5e)',
        'red-f4': 'var(--red-f4)',
        'red-27': 'var(--red-27)',
        'red-81-02': 'var(--red-81-02)',
        'green-97': 'var(--green-97)',
        'green-73': 'var(--green-73)',
        'green-87': 'var(--green-87)',
        'green-da': 'var(--green-da)',
        'green-15': 'var(--green-15)',
        'green-fa':'#ECFFFA',
        'green-66':'#25D366',
        'yellow-16': 'var(--yellow-16)',
        'yellow-00': 'var(--yellow-00)',
        'yellow-30': 'var(--yellow-30)',
        'orange-35': 'var(--orange-35)',
        'blue-ff': 'var(--blue-ff)',
        'blue-0ff':'#E3F0FF',
        'blue-f4': 'var(--blue-f4)',
        'blue-fe': 'var(--blue-fe)',
        'blue-d6': 'var(--blue-d6)',
      },
    },
  },
};
