export default () => ({
  fetching: {
    profile: false,
    subjects: false,
    exams: false,
    examsWillDo: false,
    examsProcessing: false,
    examsDone: false,
    examDetails: false,
    studentExamRepeat: false,
    examWizardDetails: false,
    examSuggestions: false,
    answer: false,
    saveNote: false,
    challengeDetail: false,
    trainReview: false,
    complaintRequest: false,
    removeAnswerHelp: false,
  },
  profile: null,
  isOpenMenu: false,
  subjects: null,
  examsWillDo: null,
  examsProcessing: null,
  examsDone: null,
  examDetails: null,
  examsWizardFilterResult: null,
  examWizardDetails: null,
  examSuggestions: null,
  currentExamTrainPageData: null,
  reviewQuestions: null,
  studentAnalytics: null,
  studentAnalyticsChart: null,
  selectedStudentIdForTeacher: null,
});
