import {
  UserPanelItems,
  UserPanelItemsRecord,
} from '~/main/constants/user-panel-items';
import { RouteHelper } from '~/main/utils/route-helper';
import { UserRoles } from './user-roles';

export const userMenuItemsIds = {
  train: 'train',
};
export const userMenuItems = [
  {
    name: 'الرئيسية',
    icon: '/images/svg/user-panel/house.svg',
    route: '/user-dashboard',
    isMobile: true,
    isDesktop: true,
    allowRoles: [],
    denyRoles: [],
  },
  {
    name: 'تأسيس',
    icon: '/images/svg/user-panel/balon.svg',
    route: '/user-dashboard/foundation',
    isMobile: true,
    isDesktop: true,
    allowRoles: [],
    denyRoles: [UserRoles.teacher, UserRoles.schoolManager],
  },
  {
    id: userMenuItemsIds.train,
    name: 'تدريب',
    icon: '/images/svg/user-panel/target.svg',
    route: `/user-dashboard/prepare?page=${UserPanelItemsRecord[UserPanelItems.trainings]}`,
    isMobile: true,
    isDesktop: true,
    allowRoles: [],
    denyRoles: [],
  },
  {
    name: 'محاكي الاختبار',
    icon: '/images/svg/user-panel/studying-exam.svg',
    route: `/user-dashboard/prepare?page=${UserPanelItemsRecord[UserPanelItems.exams]}`,
    isMobile: false,
    isDesktop: false,
    allowRoles: [],
    denyRoles: [UserRoles.teacher, UserRoles.schoolManager],
  },
  {
    name: 'سجل التدريب',
    icon: '/images/svg/user-panel/hourglass-time.svg',
    route: '/dashboard/history',
    isMobile: false,
    isDesktop: false,
    allowRoles: [],
    denyRoles: [UserRoles.teacher, UserRoles.schoolManager],
  },
  {
    name: 'خطواتي',
    icon: '/images/svg/user-panel/star.svg',
    route: '/user-dashboard/steps',
    isMobile: false,
    isDesktop: false,
    allowRoles: [],
    denyRoles: [UserRoles.teacher, UserRoles.schoolManager],
  },
  {
    name: 'تحليلاتي',
    icon: '/images/svg/user-panel/analytics.svg',
    route: '/user-dashboard/analytics',
    isMobile: true,
    isDesktop: true,
    allowRoles: [],
    denyRoles: [UserRoles.teacher, UserRoles.schoolManager],
  },
  {
    name: 'لوحة المدرب',
    icon: '/images/svg/user-panel/teacher-panel.svg',
    route: '/user-dashboard/teacher',
    isMobile: true,
    isDesktop: true,
    allowRoles: [UserRoles.teacher],
    denyRoles: [],
  },
  {
    name: 'لوحة المدرسة',
    icon: '/images/svg/user-panel/school.svg',
    route: '/user-dashboard/school',
    isMobile: true,
    isDesktop: true,
    allowRoles: [UserRoles.schoolManager,UserRoles.teacher],
    denyRoles: [],
  },
  {
    name: 'الاشتراكات',
    icon: '/images/svg/user-panel/king.svg',
    route:'/user-dashboard/personal-setting?section=subscriptions',
    isMobile: false,
    isDesktop: true,
    allowRoles: [],
    denyRoles: [UserRoles.teacher, UserRoles.schoolManager],
  },
  {
    name: 'المزيد',
    icon: '/images/svg/user-panel/more.svg',
    route: '/user-dashboard/mobile-menu',
    isMobile: true,
    isDesktop: false,
    allowRoles: [],
    denyRoles: [UserRoles.teacher, UserRoles.schoolManager],
  },
];
